name: hw-dump
version: '0.0.0.1'
synopsis: File Dump
description: Please see README.md
category: Data, Bit
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-dump
homepage: http://github.com/haskell-works/hw-dump#readme
extra-source-files:
- README.md
dependencies:
- base              >= 4          && < 5
- bytestring
- hw-bits           >= 0.7.0.3
- hw-prim           >= 0.6.2.15
- vector

library:
  source-dirs: src
  exposed-modules:
  - HaskellWorks.Data.Dump
  dependencies:
  - safe
  when:
  - condition: flag(sse42)
    then:
      ghc-options:
      - -Wall
      - -O2
      - -msse4.2
    else:
      ghc-options:
      - -Wall
      - -O2

executables:
  hw-dump:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2
    dependencies:
    - hw-dump
    - lens
    - optparse-applicative

tests:
  hw-dump-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hedgehog
    - hspec
    - hw-dump
    - hw-hspec-hedgehog
    - QuickCheck

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    dependencies:
    - criterion
    - hw-dump
    when:
    - condition: flag(sse42)
      then:
        ghc-options:
        - -Wall
        - -O2
        - -msse4.2
      else:
        ghc-options:
        - -Wall
        - -O2
flags:
  sse42:
    description: Enable SSE 4.2 optimisations.
    manual: false
    default: true
stability: Experimental
